# Generated by Django 6.0.1 on 2026-01-29 21:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('asset_type', models.CharField(choices=[('APPLICATION', 'Application'), ('REPORT', 'Report/Dashboard'), ('OP_SYSTEM', 'Operational System'), ('FACILITY', 'Facility/Site')], max_length=32)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ACTIVE', 'Active'), ('DEPRECATED', 'Deprecated'), ('RETIRED', 'Retired')], default='ACTIVE', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('business_owner', models.CharField(blank=True, max_length=200)),
                ('technical_owner', models.CharField(blank=True, max_length=200)),
                ('criticality', models.CharField(blank=True, choices=[('TIER_0', 'Tier 0 (Mission Critical)'), ('TIER_1', 'Tier 1'), ('TIER_2', 'Tier 2'), ('TIER_3', 'Tier 3')], max_length=16)),
                ('risk_security', models.BooleanField(default=False)),
                ('risk_privacy', models.BooleanField(default=False)),
                ('risk_compliance', models.BooleanField(default=False)),
                ('external_reference_url', models.URLField(blank=True)),
                ('last_reviewed_at', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_created', to=settings.AUTH_USER_MODEL)),
                ('owning_org_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='users.orgunit')),
            ],
            options={
                'indexes': [models.Index(fields=['asset_type', 'status'], name='assets_asse_asset_t_be4ea2_idx'), models.Index(fields=['name'], name='assets_asse_name_e4d2fa_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'asset_type'), name='uniq_asset_name_type')],
            },
        ),
    ]
