# Generated by Django 6.0.1 on 2026-01-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_asset_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='acronym',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
