# Generated by Django 6.0.1 on 2026-01-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_asset_acronym'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='scope',
            field=models.CharField(blank=True, choices=[('ADMINISTRATIVE', 'Administrative'), ('ADULT', 'Adult'), ('JUVENILE', 'Juvenile'), ('CROSS_CUTTING', 'Cross-Cutting'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
