# Generated by Django 6.0.1 on 2026-01-31 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_asset_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('APPLICATION', 'Application'), ('OP_SYSTEM', 'Operational System'), ('FACILITY', 'Facility/Site')], max_length=32),
        ),
    ]
