# Generated by ChatGPT on 2026-02-02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0007_asset_updated_by"),
        ("users", "0002_team_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assets",
                to="users.team",
            ),
        ),
    ]
