# Generated by Django 6.0.1 on 2026-01-31 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0004_asset_scope'),
        ('outcomes', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ACTIVE', 'Active'), ('DEPRECATED', 'Deprecated'), ('RETIRED', 'Retired')], default='ACTIVE', max_length=16)),
                ('business_owner', models.CharField(blank=True, max_length=200)),
                ('technical_owner', models.CharField(blank=True, max_length=200)),
                ('external_reference_url', models.URLField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_created', to=settings.AUTH_USER_MODEL)),
                ('owning_org_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='users.orgunit')),
            ],
        ),
        migrations.CreateModel(
            name='ReportAssetLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_links', to='assets.asset')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_links', to='reports.report')),
            ],
        ),
        migrations.CreateModel(
            name='ReportAccomplishmentLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accomplishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_links', to='outcomes.accomplishment')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accomplishment_links', to='reports.report')),
            ],
        ),
        migrations.AddConstraint(
            model_name='reportassetlink',
            constraint=models.UniqueConstraint(fields=('report', 'asset'), name='uniq_report_asset'),
        ),
        migrations.AddConstraint(
            model_name='reportaccomplishmentlink',
            constraint=models.UniqueConstraint(fields=('report', 'accomplishment'), name='uniq_report_accomplishment'),
        ),
    ]
