# Generated by Django 6.0.1 on 2026-01-31 00:00

from django.db import migrations


def forwards(apps, schema_editor):
    Asset = apps.get_model("assets", "Asset")
    Report = apps.get_model("reports", "Report")
    AccomplishmentAssetLink = apps.get_model("outcomes", "AccomplishmentAssetLink")
    ReportAccomplishmentLink = apps.get_model("reports", "ReportAccomplishmentLink")
    ProjectAssetLink = apps.get_model("projects", "ProjectAssetLink")

    report_assets = list(Asset.objects.filter(asset_type="REPORT"))
    if not report_assets:
        return

    report_asset_ids = [a.id for a in report_assets]

    for asset in report_assets:
        Report.objects.get_or_create(
            id=asset.id,
            defaults={
                "name": asset.name,
                "description": asset.description,
                "status": asset.status,
                "business_owner": asset.business_owner,
                "technical_owner": asset.technical_owner,
                "owning_org_unit_id": asset.owning_org_unit_id,
                "assigned_to_id": asset.assigned_to_id,
                "external_reference_url": asset.external_reference_url,
                "created_by_id": asset.created_by_id,
            },
        )

    # Move accomplishment-asset links to report-accomplishment links
    for link in AccomplishmentAssetLink.objects.filter(asset_id__in=report_asset_ids):
        ReportAccomplishmentLink.objects.get_or_create(
            report_id=link.asset_id,
            accomplishment_id=link.accomplishment_id,
        )

    # Remove links that pointed to report assets
    AccomplishmentAssetLink.objects.filter(asset_id__in=report_asset_ids).delete()
    ProjectAssetLink.objects.filter(asset_id__in=report_asset_ids).delete()

    # Remove report assets from assets table
    Asset.objects.filter(id__in=report_asset_ids).delete()


def backwards(apps, schema_editor):
    # No reverse migration for report split in this POC
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
        ("assets", "0004_asset_scope"),
        ("outcomes", "0001_initial"),
        ("projects", "0002_project_assigned_to"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
