# Generated by ChatGPT on 2026-02-02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0006_report_audit_fields"),
        ("users", "0002_team_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reports",
                to="users.team",
            ),
        ),
    ]
