# Generated by Django 6.0.1 on 2026-02-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_report_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='scope',
            field=models.CharField(blank=True, choices=[('ADMINISTRATIVE', 'Administrative'), ('ADULT', 'Adult'), ('JUVENILE', 'Juvenile'), ('CROSS_CUTTING', 'Cross-Cutting')], max_length=20),
        ),
    ]
