# Generated by Django 6.0.1 on 2026-01-29 21:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('projects', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accomplishment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('narrative', models.TextField(blank=True)),
                ('impact_type', models.CharField(blank=True, choices=[('RISK', 'Risk Reduction'), ('COST', 'Cost Savings / Avoidance'), ('SPEED', 'Speed / Throughput'), ('QUALITY', 'Quality / Reliability'), ('CUSTOMER', 'Customer Experience')], max_length=16)),
                ('metric', models.CharField(blank=True, max_length=255)),
                ('evidence_urls', models.TextField(blank=True, help_text='POC: paste one or more URLs (one per line). Later: normalize into a related table.')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accomplishments_created', to=settings.AUTH_USER_MODEL)),
                ('owning_org_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accomplishments', to='users.orgunit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccomplishmentAssetLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accomplishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_links', to='outcomes.accomplishment')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accomplishment_links', to='assets.asset')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('accomplishment', 'asset'), name='uniq_accomplishment_asset')],
            },
        ),
        migrations.CreateModel(
            name='AccomplishmentProjectLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accomplishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_links', to='outcomes.accomplishment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accomplishment_links', to='projects.project')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('accomplishment', 'project'), name='uniq_accomplishment_project')],
            },
        ),
    ]
