# Generated by Django 6.0.1 on 2026-01-29 21:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('project_type', models.CharField(choices=[('NEW_BUILD', 'New Build'), ('ENHANCEMENT', 'Enhancement'), ('MAINTENANCE', 'Maintenance'), ('INFRA', 'Infrastructure'), ('FACILITIES', 'Facilities'), ('SECURITY', 'Security/Compliance'), ('DISCOVERY', 'Discovery/Research')], max_length=24)),
                ('status', models.CharField(choices=[('INTAKE', 'Intake'), ('PLANNED', 'Planned'), ('ACTIVE', 'Active'), ('BLOCKED', 'Blocked'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], default='INTAKE', max_length=16)),
                ('priority', models.CharField(choices=[('P0', 'P0'), ('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3')], default='P2', max_length=4)),
                ('sponsor', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('target_end_date', models.DateField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_owned', to=settings.AUTH_USER_MODEL)),
                ('owning_org_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='users.orgunit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectAssetLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(choices=[('IMPACTS', 'Impacts'), ('ENHANCES', 'Enhances'), ('BUILDS', 'Builds'), ('REPLACES', 'Replaces'), ('DECOMMISSIONS', 'Decommissions'), ('DEPENDS_ON', 'Depends On')], max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_links', to='assets.asset')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_links', to='projects.project')),
            ],
            options={
                'indexes': [models.Index(fields=['project'], name='projects_pr_project_45df1a_idx'), models.Index(fields=['asset'], name='projects_pr_asset_i_342546_idx')],
                'constraints': [models.UniqueConstraint(fields=('project', 'asset', 'relationship_type'), name='uniq_project_asset_relationship')],
            },
        ),
    ]
