# Generated by Django 6.0.1 on 2026-01-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectassetlink',
            name='relationship_type',
            field=models.CharField(choices=[('IMPACTS', 'Impacts'), ('ENHANCES', 'Enhances'), ('MAINTAINS', 'Maintains'), ('BUILDS', 'Builds'), ('REPLACES', 'Replaces'), ('DECOMMISSIONS', 'Decommissions'), ('DEPENDS_ON', 'Depends On')], max_length=20),
        ),
    ]
