# Generated by Django 6.0.1 on 2026-01-31 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_scope'),
        ('projects', '0003_projectassetlink_add_maintains'),
    ]

    operations = [
    ]
