# Generated by Django 6.0.1 on 2026-01-31 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_task'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='projecttask',
            new_name='projects_pr_project_4795b4_idx',
            old_name='projects_pr_project_81b9ba_idx',
        ),
        migrations.RenameIndex(
            model_name='projecttask',
            new_name='projects_pr_assigne_23e72d_idx',
            old_name='projects_pr_assigned_5d0c8b_idx',
        ),
    ]
