# Generated by Django 6.0.1 on 2026-01-31 23:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_projecttask_bucket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='projecttask',
            index=models.Index(fields=['project', 'bucket'], name='projects_pr_project_36a40e_idx'),
        ),
    ]
