# Generated by Django 6.0.1 on 2026-02-01 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_projecttask_projects_pr_project_36a40e_idx'),
        ('projects', '0008_remove_projecttask_bucket'),
    ]

    operations = [
    ]
