# Generated by Django 6.0.1 on 2026-02-01 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_merge_20260131_1602'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='projecttask',
            name='projects_pr_project_36a40e_idx',
        ),
    ]
