# Generated by Django 6.0.1 on 2026-02-01 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_project_milestone'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='projectmilestone',
            new_name='projects_pr_project_42fe8f_idx',
            old_name='projects_pr_project_967ad1_idx',
        ),
        migrations.RenameIndex(
            model_name='projectmilestone',
            new_name='projects_pr_assigne_094579_idx',
            old_name='projects_pr_assigned_6428ed_idx',
        ),
        migrations.RenameIndex(
            model_name='projectmilestone',
            new_name='projects_pr_due_dat_bdd41c_idx',
            old_name='projects_pr_due_date_8a6319_idx',
        ),
    ]
