# Generated by ChatGPT on 2026-02-02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0013_rename_projects_pr_project_967ad1_idx_projects_pr_project_42fe8f_idx_and_more"),
        ("users", "0002_team_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="users.team",
            ),
        ),
    ]
