# Generated by Django 6.0.1 on 2026-02-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_project_issue_and_task_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='owning_team',
            field=models.CharField(blank=True, choices=[('BADM', 'BADM'), ('PMO', 'PMO'), ('IO', 'IO'), ('ITSO', 'ITSO')], max_length=8),
        ),
    ]
