# Generated by Django 6.0.1 on 2026-02-01 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='document',
            new_name='documents_d_target__a509ac_idx',
            old_name='documents_do_target__b2b5c7_idx',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='documents_d_created_3b0a51_idx',
            old_name='documents_do_created_4de0e7_idx',
        ),
    ]
