# Generated by ChatGPT on 2026-02-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_rename_documents_do_target__b2b5c7_idx_documents_d_target__a509ac_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="category",
            field=models.CharField(
                choices=[
                    ("BRD", "BRD"),
                    ("ERD", "ERD"),
                    ("PROPOSAL", "Proposal"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="version",
            field=models.DecimalField(decimal_places=1, default=0.1, max_digits=4),
        ),
    ]
