# Generated by Django 6.0.1 on 2026-01-29 21:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaggedItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('ASSET', 'Asset'), ('PROJECT', 'Project'), ('ACCOMPLISHMENT', 'Accomplishment')], max_length=32)),
                ('target_id', models.UUIDField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tags', to=settings.AUTH_USER_MODEL)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='core.tag')),
            ],
            options={
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='core_tagged_target__b46c43_idx'), models.Index(fields=['tag'], name='core_tagged_tag_id_58eade_idx')],
                'constraints': [models.UniqueConstraint(fields=('tag', 'target_type', 'target_id'), name='uniq_tag_target')],
            },
        ),
    ]
