# Generated by Django 6.0.1 on 2026-02-01 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_audit_log_and_userstamps'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_app_lab_7bfe1d_idx',
            old_name='core_auditlog_lookup_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_created_dc23ea_idx',
            old_name='core_auditlog_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_actor_i_870709_idx',
            old_name='core_auditlog_actor_idx',
        ),
    ]
